// packages/demo-apps/vue26/src/App.vue
<script lang="ts">
import { defineComponent, ref } from "@vue/composition-api";
import { VMyAccordion, VMyCard } from "@sterashima78/lit-practice-vue26";
export default defineComponent({
  components: {
    VMyAccordion,
    VMyCard,
  },
  setup() {
    const isOpen = ref(true);
    const log = (a: unknown) => console.log(a);
    return {
      isOpen,
      log,
    };
  },
});
</script>

<template>
  <div>
    <label>Toggle <input v-model="isOpen" type="checkbox" /></label>
    <VMyAccordion
      :is-open="isOpen"
      @toggle="({ isOpen: open }) => (isOpen = open)"
    >
      <template #header>
        <a href="https://vitejs.dev" target="_blank">
          <img src="/vite.svg" class="logo" alt="Vite logo" />
        </a>
        <a href="https://vuejs.org/" target="_blank">
          <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
        </a>
      </template>
      <VMyCard>
        <template #header>
          <p>Header</p>
        </template>
        <button @click="log('click')">log</button>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
      </VMyCard>
    </VMyAccordion>
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// packages/demo-apps/react/src/App.tsx
import { MyAccordion, MyCard } from "@sterashima78/lit-practice-react";
import { useState } from "react";
import reactLogo from "./assets/react.svg";
import "./App.css";

function App() {
  const [count, setCount] = useState(0);
  const [isOpen, setIsOpen] = useState(true);
  const [isUseLogger, setIsUseLogger] = useState(true);

  return (
    <div className="App">
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src="/vite.svg" className="logo" alt="Vite logo" />
        </a>
        <a href="https://reactjs.org" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <label>
        <input type="checkbox" onChange={() => setIsOpen(!isOpen)} checked={isOpen} />
        Toggle Accordion
      </label>

      <label>
        <input type="checkbox" onChange={() => setIsUseLogger(!isUseLogger)} checked={isUseLogger} />
        with Logger
      </label>

      <MyAccordion
        isOpen={isOpen}
        onToggle={isUseLogger
          ? ({ isOpen }) => {
            setIsOpen(isOpen);
            console.log(`set isOpen=${isOpen}`);
          }
          : ({ isOpen }) => setIsOpen(isOpen)}
      >
        <h1 slot="header">Vite + React</h1>
        <MyCard>
          <p slot="header">Counter</p>
          <button onClick={() => setCount((count) => count + 1)}>
            count is {count}
          </button>
        </MyCard>
      </MyAccordion>
    </div>
  );
}

export default App;
